# Generated by Django 3.2.7 on 2022-07-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('income_amount', models.CharField(max_length=10, verbose_name='income_amount')),
                ('date', models.CharField(max_length=20, verbose_name='date')),
            ],
        ),
    ]
